SPICY_SOUNDS = [
    "sounds/arnold/bullsh_dont.wav",
    "sounds/arnold/fist.wav",
    "sounds/arnold/no_sh.wav",
    "sounds/arnold/sob.wav",
    "sounds/arnold/t1_fu.wav",
    "sounds/arnold/ugly.wav",
    "sounds/bender/Bodies are for hookers.mp3",
    "sounds/bender/Compare your lives to mine.mp3",
    "sounds/bender/Dont make me kick your neck.mp3",
    "sounds/bender/Im gonna go kill my self.mp3",
    "sounds/bender/Lets go get drunk.mp3",
    "sounds/bender/That dirty bastard.mp3",
    "sounds/bender/Wanna kill all humans.mp3",
]
